#!/usr/bin/env python3
"""
Stargaze Engine Log Parser
===========================
This script parses game logs generated by the Stargaze chess engine,
validates all the moves using python-chess, converts them to proper
Standard Algebraic Notation (SAN), and outputs a clean PGN file.

If an illegal move is detected in the log (due to older versions of the
engine allowing king-to-king adjacency or moving into check), the script
automatically prints a warning to stderr and truncates the game output
to the last completely legal move so it remains importable in standard
chess viewers (e.g. chess.com or lichess).

Usage:
------
1. Output PGN to stdout:
   $ python3 tools/parse_log.py crazy-game.log

2. Output PGN to a file:
   $ python3 tools/parse_log.py crazy-game.log -o crazy-game.pgn

Arguments:
----------
  log_file              Path to the Stargaze engine .log file to parse.
  -o, --output          (Optional) Path to write the PGN file.
"""

import argparse
import os
import re
import sys

import chess
import chess.pgn


def sq_to_name(sq):
    file_idx = sq % 8
    rank_idx = sq // 8
    file_char = chr(ord("a") + file_idx)
    rank_char = chr(ord("1") + rank_idx)
    return file_char + rank_char


def parse_log(log_file):
    if not os.path.exists(log_file):
        print(f"Error: Log file '{log_file}' not found.", file=sys.stderr)
        sys.exit(1)

    with open(log_file, "r") as f:
        content = f.read()

    # Regex to find move result lines:
    # -> [result: {depth: ..., pv: {[FROM TO FLAGS], ...}, ...}]
    pattern = r"->\s*\[result:\s*\{[^}]*pv:\s*\{\s*\[([a-h][1-8]|\d+)\s+([a-h][1-8]|\d+)\s+(\d+)\]"
    matches = list(re.finditer(pattern, content))

    uci_moves = []
    for match in matches:
        from_val = match.group(1)
        to_val = match.group(2)
        flags = int(match.group(3))

        from_name = sq_to_name(int(from_val)) if from_val.isdigit() else from_val
        to_name = sq_to_name(int(to_val)) if to_val.isdigit() else to_val

        # Determine promotion piece if any
        prom = ""
        if (flags & 8) != 0:
            specials = flags & 3
            if specials == 0:
                prom = "n"
            elif specials == 1:
                prom = "b"
            elif specials == 2:
                prom = "r"
            else:
                prom = "q"

        uci_move = f"{from_name}{to_name}{prom}"
        uci_moves.append(uci_move)

    return uci_moves


def validate_and_generate_pgn(uci_moves, filename_tag="Stargaze Engine"):
    board = chess.Board()
    legal_uci_moves = []
    illegal_index = -1

    for i, uci in enumerate(uci_moves):
        move = chess.Move.from_uci(uci)
        if move in board.legal_moves:
            legal_uci_moves.append((uci, board.san(move)))
            board.push(move)
        else:
            illegal_index = i
            print(
                f"Warning: Illegal move found at index {i} ({board.fullmove_number}. {'...' if not board.turn else ''} {uci}). Truncating game here.",
                file=sys.stderr,
            )
            break

    # Generate PGN up to the last legal move
    game = chess.pgn.Game()
    game.headers["Event"] = f"{filename_tag} Game"
    game.headers["Site"] = "Localhost"
    game.headers["Date"] = "2026.06.13"
    game.headers["Round"] = "1"
    game.headers["White"] = "Stargaze (White)"
    game.headers["Black"] = "Stargaze (Black)"

    node = game
    for uci, san in legal_uci_moves:
        move = chess.Move.from_uci(uci)
        node = node.add_main_variation(move)

    if illegal_index == -1:
        # Full game was legal, check if checkmate or draw
        if board.is_checkmate():
            result = "1-0" if board.turn == chess.BLACK else "0-1"
        elif (
            board.is_stalemate()
            or board.is_insufficient_material()
            or board.is_fifty_moves()
        ):
            result = "1/2-1/2"
        else:
            result = "*"
    else:
        result = "*"

    game.headers["Result"] = result
    return game


def main():
    parser = argparse.ArgumentParser(
        description="Parse Stargaze engine game logs and output a clean PGN."
    )
    parser.add_argument("log_file", help="Path to the Stargaze engine .log file")
    parser.add_argument(
        "-o", "--output", help="Path to write the PGN file (default: stdout)"
    )

    args = parser.parse_args()

    tag = os.path.basename(args.log_file).replace(".log", "").replace("-", " ").title()

    uci_moves = parse_log(args.log_file)
    if not uci_moves:
        print("Error: No moves found in the log file.", file=sys.stderr)
        sys.exit(1)

    game = validate_and_generate_pgn(uci_moves, tag)

    if args.output:
        with open(args.output, "w") as f:
            f.write(str(game))
        print(f"PGN successfully written to {args.output}", file=sys.stderr)
    else:
        print(game)


if __name__ == "__main__":
    main()
